### ISSUE TITLE
Segmentation fault 

### ISSUE THREAD

**Issue by merrygoat** [royallgroup/TCC#113]
A report by Cristian Balbuena of a segmentation fault when using NPT or Triclinic boundary conditions.

**Comment by merrygoat** [comment]
A few questions to help narrow down the issue:

What operating system are you using?
Which C compiler and version are you using?
What version of the code are you using?
When you run the automated tests described at the bottom of this page do they work? https://royallgroup.github.io/TCC/html/setup.html#to-build-on-windows-with-mingw

**Comment by cristianbalbuena** [comment]
Peter, I found my mistake. The number of lines/frames in box.txt must be at least the number of frames in the .xyz and not the number of frames in the inputparameters.ini.
Thanks for the contribution!
Cristian

**Comment by merrygoat** [comment]
Thank you for that, it should at least give a sensible warning message and not crash though, I will check this.

Although the TCC has been in development for some time, it has only been recently released publicly and so feedback from real world users is very valuable. If you find any more bugs or have suggestions for features or improvements please create another issue and we will look into it.

**Comment by merrygoat** [comment]
I have manually tested a number of possible configurations of box, inputparameters and xyz files and am happier with how this works now. There should be no crashes and error messages should be much more informative.

This really could do with some proper unit tests for the file read functions but this is hard because of the number of global variables. This can be part of a future restructure to C++. When the code is written properly from the beginning it will be easier to unit test.
