### ISSUE TITLE
Suggestion: C documentation could be incorporated with Breathe

### ISSUE THREAD

**Issue by tranqui** [royallgroup/TCC#114]
Currently the documentation page is generated from Sphinx, which is traditionally designed for documenting python code. As the core of the TCC is written in C++ it would be nice to incorporate its documentation into these pages. An option for doing this would be to build the C++ documentation using doxygen, and incorporate this into the current documentation using Breathe.

The documentation for Breathe can be found:
https://breathe.readthedocs.io/en/latest/

**Comment by tranqui** [comment]
This would require reformatting of current C++ documentation in doxygen (and presumably expanding current documentation and filling in missing documentation), extending the build process to perform the new compilation steps (doxygen + breathe) and writing additional text in the current Sphinx documentation giving an overview of the new docs.

**Comment by merrygoat** [comment]
The mechanics of this have been set up and some of the source code is well commented, mostly the specific cluster files. The rest of the documentation can be brought up to scratch as it is worked on.
