### ISSUE TITLE
errors running cluster_movie_maker

### ISSUE THREAD

**Issue by ursacavebear** [royallgroup/TCC#126]
Hi Peter

I get the following error:

Traceback (most recent call last):
  File "cluster_movie_maker.py", line 234, in <module>
    main()
  File "cluster_movie_maker.py", line 54, in main
    cluster_types = raw_file.get_frame()
  File "cluster_movie_maker.py", line 177, in get_frame
    self.num_particles = int(self.file_handle.readline())
ValueError: invalid literal for int() with base 10: ''

Is there any test data to check this with?

cheers

Paddy

**Comment by merrygoat** [comment]
This would suggest an issue with your RAW files. If they are old, try rerunning the TCC on the same xyz and use the newly generated RAW files... I don't think the RAW files changed format in the last couple of years but they may have done.
