### ISSUE TITLE
Trajectory with more than 1000 frames

### ISSUE THREAD

**Issue by FTurci** [royallgroup/TCC#128]
I have tried to analyse a trajectory with more than 1000 frames using the latest master version. I get the message 

"XYZ file has over 1000 frames, cannot process XYZ file"

I do not see why we would have a hard, non configurable limit at 1000 frames. In the code, it seems that the values is even hardcoded. 

I propose, at least, that we should use a #define directive so that the number can be changed at compilation time.

**Comment by merrygoat** [comment]
It's something to do with mallocing the cluster storage arrays as far as I can remember. I'll have a look.

**Comment by merrygoat** [comment]
Tested to work on over 1000 frames and valgrind says I have no memory leaks so we should be good but let me know if this breaks anything.
