### ISSUE TITLE
Python Wrapper: "No such file or directory".

### ISSUE THREAD

**Issue by bc1032** [royallgroup/TCC#90]
Temporary file is being deleted before analysis.

Commenting out Line 247 in wrapper.py stops this error from occurring.

**Comment by merrygoat** [comment]
Having worked some more on the wrapper this is probably a misunderstanding of what the wrapper does. The wrapper has been extensively rewritten and documented, with documentation in  df3b7f6ff9162239b90fe99a5bce6c31635c462c. This will be merged into master later this week.
