### ISSUE TITLE
make install attempting wrong path 

### ISSUE THREAD

**Issue by FTurci** [royallgroup/TCC#98]
I have pull from devel today and attempted a make, make install on bluecrystall  P3. It looks like make install attempts to install the tcc in an odd path ("/usr/local/tcc").

I think that it should first try something like $HOME/bin and then /usr/local/bin.

Here is the output:

> [  6%] Built target iniparser
> [100%] Built target tcc
> Install the project...
> -- Install configuration: ""
> -- Installing: /usr/local/tcc
> CMake Error at src/cmake_install.cmake:50 (file):
>   file INSTALL cannot copy file
>   "/panfs/panasas01/phys/ft14968/Royall_Github/TCC/build/src/tcc" to
>   "/usr/local/tcc".
> Call Stack (most recent call first):
>   cmake_install.cmake:38 (include)
> 
> 
> make: *** [install] Error 1

**Comment by merrygoat** [comment]
Works fine for me....

```
>> make install
[  6%] Built target iniparser
[100%] Built target tcc
Install the project...
-- Install configuration: ""
-- Installing: /panfs/panasas01/chem/pc9836/TCC/bin/tcc
>>
```
It should default to the bin directory in the same directory as the build directory. What make version are you using? I'm on 3.81. More hints can probably be found in the build/cmake_install.cmake file.

You can try forcing to a specific location by using the command 
`cmake .. -DCMAKE_INSTALL_PREFIX:PATH=$HOME` 
which also works for me.
